IF %_BATCHINSTALLER.EXE%==1 goto :BATCHINSTALLER.EXE
IF %_CALCULATOR.EXE%==1 goto :CALCULATOR.EXE
IF %_CALENDAR.EXE%==1 goto :CALENDAR.EXE
IF %_CLOCK.EXE%==1 goto :CLOCK.EXE
IF %_EDGE.EXE%==1 goto :EDGE.EXE
IF %_EXPLORER.EXE%==1 goto :EXPLORER.EXE
IF %_FEEDBACKHUB.EXE%==1 goto :FEEDBACKHUB.EXE
IF %_NOTEPAD.EXE%==1 goto :NOTEPAD.EXE
IF %_PAINT.EXE%==1 goto :PAINT.EXE
IF %_PHOTOS.EXE%==1 goto :PHOTOS.EXE
IF %_SETTINGS.EXE%==1 goto :SETTINGS.EXE
IF %_SECURITY.EXE%==1 goto :SECURITY.EXE
IF %_TERMINAL.EXE%==1 goto :TERMINAL.EXE
IF %_SNIPTOOL.EXE%==1 goto :SNIPTOOL.EXE
IF %_TASKMGR.EXE%==1 goto :TASKMGR.EXE
IF %_TIPS.EXE%==1 goto :TIPS.EXE
exit /b